# Generated by Django 3.0 on 2019-12-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='reached',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='reached_date',
        ),
        migrations.AlterField(
            model_name='milestone',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('reached', 'Reached'), ('not reached', 'Not Reached')], default='not reached', max_length=20),
        ),
    ]
