# Generated by Django 3.0 on 2019-12-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191218_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='supplemental_example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
