# Generated by Django 3.0 on 2019-12-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_knowledgeandtips_thingstoconsider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thingstoconsider',
            options={'ordering': ('ranking',)},
        ),
        migrations.AddField(
            model_name='thingstoconsider',
            name='ranking',
            field=models.CharField(choices=[('high importance (1)', 'High Importance (1)'), ('medium importance (2)', 'Medium Importance (2)'), ('low importance (3)', 'Low Importance (3)')], default='medium importance', max_length=25),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ranking',
            field=models.CharField(choices=[('dealbreaker (1)', 'Dealbreaker (1)'), ('very important (2)', 'Very Important (2)'), ('important (3)', 'Important (3)'), ('kind of important (4)', 'Kind of Important (4)'), ('almost petty (5)', 'Almost Petty (5)'), ('definitely petty (6)', 'Definitely Petty (6)')], default='kind of important', max_length=25),
        ),
    ]
