# Generated by Django 3.0 on 2019-12-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191219_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorplan_name', models.CharField(max_length=100)),
                ('community_name', models.CharField(max_length=100)),
                ('builder_name', models.CharField(max_length=100)),
                ('property_slug', models.SlugField(max_length=300, null=True, unique=True)),
                ('cover', models.ImageField(upload_to='images/')),
                ('floorplan_link', models.URLField()),
                ('ranking', models.CharField(choices=[('current favorite (1)', 'Current favorite (1)'), ('backup favorite (1.5)', 'Backup favorite (1.5)'), ('really like it (2)', 'Really like it (2)'), ('like it (3)', 'Like it (3)'), ('acceptable, but least favorite (4)', 'Acceptable, but least favorite (4)')], default='really like it (2)', max_length=40)),
                ('square_footage', models.IntegerField()),
                ('bedrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 and up', '5 & up')], default='1', max_length=10)),
                ('bathrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 and up', '5 & up')], default='1', max_length=10)),
                ('garage', models.CharField(choices=[('1 car', '1 car'), ('1 car with nook', '1 car with nook'), ('2 car', '2 car'), ('2 car with nook', '2 car with nook'), ('3 car', '3 car'), ('3 car with nook', '3 car with nook')], default='1 car', max_length=20)),
                ('optional_floorplan_info', models.TextField(blank=True, null=True)),
                ('standout_features', models.TextField(blank=True, null=True)),
                ('desired_options', models.TextField(blank=True, null=True)),
                ('rounded_total_price', models.CharField(choices=[('$ 190 k', '$ 190 k'), ('$ 191 k', '$ 191 k'), ('$ 192 k', '$ 192 k'), ('$ 193 k', '$ 193 k'), ('$ 194 k', '$ 194 k'), ('$ 195 k', '$ 195 k'), ('$ 196 k', '$ 196 k'), ('$ 197 k', '$ 197 k'), ('$ 198 k', '$ 198 k'), ('$ 199 k', '$ 199 k'), ('$ 200 k', '$ 200 k'), ('$ 201 k', '$ 201 k'), ('$ 202 k', '$ 202 k'), ('$ 203 k', '$ 203 k'), ('$ 204 k', '$ 204 k'), ('$ 205 k', '$ 205 k'), ('$ 206 k', '$ 206 k'), ('$ 207 k', '$ 207 k'), ('$ 208 k', '$ 208 k'), ('$ 209 k', '$ 209 k'), ('$ 210 k', '$ 210 k'), ('$ 211 k', '$ 211 k'), ('$ 212 k', '$ 212 k'), ('$ 213 k', '$ 213 k'), ('$ 214 k', '$ 214 k'), ('$ 215 k', '$ 215 k'), ('$ 216 k', '$ 216 k'), ('$ 217 k', '$ 217 k'), ('$ 218 k', '$ 218 k'), ('$ 219 k', '$ 219 k'), ('$ 220 k', '$ 220 k'), ('$ 221 k', '$ 221 k'), ('$ 222 k', '$ 222 k'), ('$ 223 k', '$ 223 k'), ('$ 224 k', '$ 224 k'), ('$ 225 k', '$ 225 k'), ('$ 226 k', '$ 226 k'), ('$ 227 k', '$ 227 k'), ('$ 228 k', '$ 228 k'), ('$ 229 k', '$ 229 k'), ('$ 230 k', '$ 230 k'), ('$ 231 k', '$ 231 k'), ('$ 232 k', '$ 232 k'), ('$ 233 k', '$ 233 k'), ('$ 234 k', '$ 234 k'), ('$ 235 k', '$ 235 k'), ('$ 236 k', '$ 236 k'), ('$ 237 k', '$ 237 k'), ('$ 238 k', '$ 238 k'), ('$ 239 k', '$ 239 k'), ('$ 240 k', '$ 240 k'), ('$ 241 k', '$ 241 k'), ('$ 242 k', '$ 242 k'), ('$ 243 k', '$ 243 k'), ('$ 244 k', '$ 244 k'), ('$ 245 k', '$ 245 k'), ('$ 246 k', '$ 246 k'), ('$ 247 k', '$ 247 k'), ('$ 248 k', '$ 248 k'), ('$ 249 k', '$ 249 k'), ('$ 250 k', '$ 250 k'), ('$ 251 k', '$ 251 k'), ('$ 252 k', '$ 252 k'), ('$ 253 k', '$ 253 k'), ('$ 254 k', '$ 254 k'), ('$ 255 k', '$ 255 k'), ('$ 256 k', '$ 256 k'), ('$ 257 k', '$ 257 k'), ('$ 258 k', '$ 258 k'), ('$ 259 k', '$ 259 k'), ('$ 260 k', '$ 260 k'), ('$ 261 k', '$ 261 k'), ('$ 262 k', '$ 262 k'), ('$ 263 k', '$ 263 k'), ('$ 264 k', '$ 264 k'), ('$ 265 k', '$ 265 k'), ('$ 266 k', '$ 266 k'), ('$ 267 k', '$ 267 k'), ('$ 268 k', '$ 268 k'), ('$ 269 k', '$ 269 k'), ('$ 270 k', '$ 270 k'), ('$ 271 k', '$ 271 k'), ('$ 272 k', '$ 272 k'), ('$ 273 k', '$ 273 k'), ('$ 274 k', '$ 274 k'), ('$ 275 k', '$ 275 k'), ('$ 276 k', '$ 276 k'), ('$ 277 k', '$ 277 k'), ('$ 278 k', '$ 278 k'), ('$ 279 k', '$ 279 k'), ('$ 280 k', '$ 280 k'), ('$ 281 k', '$ 281 k'), ('$ 282 k', '$ 282 k'), ('$ 283 k', '$ 283 k'), ('$ 284 k', '$ 284 k'), ('$ 285 k', '$ 285 k'), ('$ 286 k', '$ 286 k'), ('$ 287 k', '$ 287 k'), ('$ 288 k', '$ 288 k'), ('$ 289 k', '$ 289 k'), ('$ 290 k', '$ 290 k'), ('$ 291 k', '$ 291 k'), ('$ 292 k', '$ 292 k'), ('$ 293 k', '$ 293 k'), ('$ 294 k', '$ 294 k'), ('$ 295 k', '$ 295 k'), ('$ 296 k', '$ 296 k'), ('$ 297 k', '$ 297 k'), ('$ 298 k', '$ 298 k'), ('$ 299 k', '$ 299 k'), ('$ 300 k', '$ 300 k'), ('$ 301 k', '$ 301 k'), ('$ 302 k', '$ 302 k'), ('$ 303 k', '$ 303 k'), ('$ 304 k', '$ 304 k'), ('$ 305 k', '$ 305 k'), ('$ 306 k', '$ 306 k'), ('$ 307 k', '$ 307 k'), ('$ 308 k', '$ 308 k'), ('$ 309 k', '$ 309 k')], default='$ 190 k', max_length=8)),
            ],
            options={
                'ordering': ('ranking',),
            },
        ),
        migrations.AlterField(
            model_name='thingstoconsider',
            name='ranking',
            field=models.CharField(choices=[('high importance (1)', 'High Importance (1)'), ('medium importance (2)', 'Medium Importance (2)'), ('low importance (3)', 'Low Importance (3)')], default='medium importance (2)', max_length=25),
        ),
    ]
