# Generated by Django 3.0 on 2019-12-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191223_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_slug',
            new_name='slug',
        ),
    ]
